microsoft/azure-devops-dotnet-samples

VSTSRestApiSamples.UnitTests/VstsRestApiSamples.Tests.csproj
VSTSRestApiSamples.UnitTests/WorkItemTracking/BatchTest.cs
VSTSRestApiSamples/ViewModels/WorkItemTracking/WorkItemBatchPost.cs
VSTSRestApiSamples/ViewModels/WorkItemTracking/WorkItemBatchPostResponse.cs
VSTSRestApiSamples/VstsRestApiSamples.csproj
VSTSRestApiSamples/WorkItemTracking/Batch.cs

@danhellem, would love feedback on this before integrating.  Once you sign off, I'll write up the doc version of this too...

Adding sample code for using the $Batch endpoint

---

VstsClientLibrariesSamples/GettingStarted/Authentication.cs
VstsClientLibrariesSamples/ProjectsAndTeams/Processes.cs
VstsClientLibrariesSamples/ProjectsAndTeams/ProjectCollections.cs
VstsClientLibrariesSamples/ProjectsAndTeams/Samples.cs
VstsClientLibrariesSamples/ProjectsAndTeams/TeamProjects.cs
VstsClientLibrariesSamples/ProjectsAndTeams/Teams.cs
VstsClientLibrariesSamples/Work/TeamSettings.cs
VstsClientLibrariesSamples/WorkItemTracking/Attachments.cs
VstsClientLibrariesSamples/WorkItemTracking/ClassificationNodes.cs
VstsClientLibrariesSamples/WorkItemTracking/ClassificationNodesSamples.cs
VstsClientLibrariesSamples/WorkItemTracking/Fields.cs
VstsClientLibrariesSamples/WorkItemTracking/Queries.cs
VstsClientLibrariesSamples/WorkItemTracking/RecycleBin.cs
VstsClientLibrariesSamples/WorkItemTracking/Sample.cs
VstsClientLibrariesSamples/WorkItemTracking/WorkItems.cs

@danhellem, this is the new standard way of getting HTTPClients per @WillSmyte

Getting HttpClient from VssConnection (new standard)

---

VstsClientLibrariesSamples.Tests/ProjectsAndTeams/ProjectCollectionsTest.cs
VstsClientLibrariesSamples.Tests/ProjectsAndTeams/TeamProjectsTest.cs
VstsClientLibrariesSamples.Tests/ProjectsAndTeams/TeamsTest.cs
VstsClientLibrariesSamples.Tests/Work/TeamSettingsTest.cs
VstsClientLibrariesSamples/GettingStarted/Authentication.cs
VstsClientLibrariesSamples/ProjectsAndTeams/Processes.cs
VstsClientLibrariesSamples/ProjectsAndTeams/ProjectCollections.cs
VstsClientLibrariesSamples/ProjectsAndTeams/TeamProjects.cs
VstsClientLibrariesSamples/ProjectsAndTeams/Teams.cs
VstsClientLibrariesSamples/VstsClientLibrariesSamples.csproj
VstsClientLibrariesSamples/Work/TeamSettings.cs
VstsClientLibrariesSamples/WorkItemTracking/Attachments.cs
VstsClientLibrariesSamples/WorkItemTracking/ClassificationNodesSamples.cs
VstsClientLibrariesSamples/WorkItemTracking/Fields.cs
VstsClientLibrariesSamples/WorkItemTracking/Queries.cs
VstsClientLibrariesSamples/WorkItemTracking/RecycleBin.cs
VstsClientLibrariesSamples/WorkItemTracking/Sample.cs
VstsClientLibrariesSamples/WorkItemTracking/WorkItems.cs
VstsClientLibrariesSamples/packages.config

The last update didn't build.  Fixing all the build warnings

Updating references to VSSConnection

---

Microsoft.TeamServices.Samples.Client.Runner/Microsoft.TeamServices.Samples.Client.Runner.csproj
Microsoft.TeamServices.Samples.Client.Runner/packages.config
Microsoft.TeamServices.Samples.Client.Test/Microsoft.TeamServices.Samples.Client.Test.csproj
Microsoft.TeamServices.Samples.Client.Test/packages.config
Microsoft.TeamServices.Samples.Client/ClientSampleHttpLogger.cs
Microsoft.TeamServices.Samples.Client/Graph/GroupsSample.cs
Microsoft.TeamServices.Samples.Client/Graph/MembershipSample.cs
Microsoft.TeamServices.Samples.Client/Graph/UsersSample.cs
Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
Microsoft.TeamServices.Samples.Client/Notification/SubscriptionsSample.cs
Microsoft.TeamServices.Samples.Client/WorkItemTracking/RecycleBinSample.cs
Microsoft.TeamServices.Samples.Client/app.config
Microsoft.TeamServices.Samples.Client/packages.config
README.md

Adding samples for the Graph REST API preview

Graph API samples

---

Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
Microsoft.TeamServices.Samples.Client/WorkItemTracking/TagsSample.cs

Tag Samples for https://www.visualstudio.com/en-us/docs/integrate/api/wit/tags

Work Item Tags Samples

---

Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
Microsoft.TeamServices.Samples.Client/WorkItemTracking/RevisionsSample.cs
Microsoft.TeamServices.Samples.Client/WorkItemTracking/UpdatesSample.cs

Samples for revisions and updates
https://www.visualstudio.com/en-us/docs/integrate/api/wit/revisions
https://www.visualstudio.com/en-us/docs/integrate/api/wit/updates

wit revisions and updates samples

---

Microsoft.TeamServices.Samples.Client/ClientSampleHelpers.cs
Microsoft.TeamServices.Samples.Client/WorkItemTracking/QueriesSample.cs

wit queries samples

---

Microsoft.TeamServices.Samples.Client/WorkItemTracking/QueriesSample.cs

Updated Queries Samples to fix problems in Issue #29

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Tfvc/BranchesSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Tfvc/ChangesetChangesSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Tfvc/ChangesetsSample.cs

Address #42 by adding TFVC samples

Add TFVC samples

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Security/AccessControlListsSample.cs

also CRLF cleanup in this file

remove dev15-only syntax

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Runner/Microsoft.TeamServices.Samples.Client.Runner.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Runner/packages.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Test/Microsoft.TeamServices.Samples.Client.Test.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Test/packages.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Graph/DescriptorsSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Graph/GroupsSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Graph/MembershipSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Graph/MembershipStatesSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Graph/StorageKeySample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Graph/SubjectLookupSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Graph/UsersSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/packages.config

The Graph REST API is shipping as a public preview with S122 so adding samples for all public calls

Adding samples for Graph REST API

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTracking/WorkItemsIconSample.cs

Added a sample to generate the icon list.
@willsmythe  I would also like to document the individual call to get the SVG, but not sure how that can work since we just output JSON.

Add sample for Work Item Icon List

---

ClientLibrary/Quickstarts/dotnet/MaterializeUserQuickStarts/App.config
ClientLibrary/Quickstarts/dotnet/MaterializeUserQuickStarts/MaterializeUserQuickStarts.csproj
ClientLibrary/Quickstarts/dotnet/MaterializeUserQuickStarts/MaterializeUserQuickStarts.sln
ClientLibrary/Quickstarts/dotnet/MaterializeUserQuickStarts/Program.cs
ClientLibrary/Quickstarts/dotnet/MaterializeUserQuickStarts/Properties/AssemblyInfo.cs
ClientLibrary/Quickstarts/dotnet/MaterializeUserQuickStarts/packages.config

This is especially useful for service accounts that don't have interactive login permissions.  The service account can be materialized through this sample and then can create PATs as needed.

Adding New example for materializing a user in an account.  

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Runner/Microsoft.TeamServices.Samples.Client.Runner.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/ClientSampleHttpLogger.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj

Fix where query parameters weren't getting included in the HTTP output files.

Fix issue with query params not getting included in HTTP output

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/packages.config

Also updates to sprint 130 packages.

Added ServiceHooks NuGet package.

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/packages.config

Also updated packages to sprint 130.

Added ServiceHooks NuGet package

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTracking/WorkItemsSample.cs

Added sample to update using validateOnly

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTracking/CommentsSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTracking/RecycleBinSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTracking/WorkItemsSample.cs

added sample to load all child work items for a parent

---

ClientLibrary/Quickstarts/dotnet/GraphQuickStarts/Program.cs
ClientLibrary/Quickstarts/dotnet/GraphQuickStarts/Samples/EnumerateUsers.cs

Extending the enumerate users sample to also enumerate group memberships for each user per the request in #118

Adding Sample to enumerate groups a user is a member of #118

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Runner/packages.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Test/packages.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Git/ItemsSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/packages.config

Add a Git GetItem sample

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Runner/App.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Runner/Microsoft.TeamServices.Samples.Client.Runner.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Runner/packages.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Test/Microsoft.TeamServices.Samples.Client.Test.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Test/app.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Test/packages.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Work/TeamSettingsSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTracking/WorkItemsSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/app.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/packages.config

Created sample for issue #149 
Updated nuget packages to latest

Created sample for #149

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Runner/App.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Runner/Microsoft.TeamServices.Samples.Client.Runner.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Runner/packages.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Test/Microsoft.TeamServices.Samples.Client.Test.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Test/app.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Test/packages.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTracking/ProcessSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTrackingProcess/ProcessesSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/app.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/packages.config

add process samples and update to latest preview version of client libs

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTrackingProcess/ProcessesSample.cs

added more process samples

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTrackingProcess/ProcessHelper.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTrackingProcess/ProcessesSample.cs

Add helper to find layout values easier

Add group to a process

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Test/TestCaseSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Test/TestConfigurationSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Test/TestPlanSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Test/TestSuiteByCaseSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Test/TestSuiteEntrySample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Test/TestSuiteSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Test/TestVariableSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/packages.config

Also updated the nuget package, which is required for these samples.

Added Samples for the test area

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTracking/ClientOMDeprecationSamples.cs

added sample to validate a work item required fields and rules

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/ClientSampleHelpers.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Release/GatesSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Release/ManualInterventionSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Release/ReleaseAttachmentSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Release/ReleasesSample.cs

Releated to PR https://github.com/Microsoft/vsts-dotnet-samples/pull/68

Added MI samples.

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/TaskGroups/TaskGroupsSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/packages.config

Changes from PR https://github.com/Microsoft/vsts-dotnet-samples/pull/90

Added task group sample

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTrackingProcess/ProcessesSample.cs

process samples for adding field to wit

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/DeploymentGroups/DeploymentGroupsSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/TaskGroups/TaskGroupsSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/packages.config

Deployment group sample snippet

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Wiki/Helpers.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Wiki/WikiPagesSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/packages.config

- Adding Samples for new API: WikiPageById under Wiki Page resource

Adding Wiki Samples

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Runner/App.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Runner/Microsoft.TeamServices.Samples.Client.Runner.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Runner/packages.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Test/Microsoft.TeamServices.Samples.Client.Test.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Test/app.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client.Test/packages.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Microsoft.TeamServices.Samples.Client.csproj
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTrackingProcess/ProcessesSample.cs
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/app.config
ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/packages.config

add fields to group in process and updating nuget packages

---

ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTracking/RecycleBinSample.cs

I'm about to PR a doc fix for the typo to go with this

typo: Permenently -> Permanently

---

ClientLibrary/Samples/Work/BoardsSample.cs
ClientLibrary/Samples/WorkItemTracking/WorkItemsSample.cs

update wef field to set the work item on the board column

---

ClientLibrary/Samples/Audit/AuditLogSample.cs
ClientLibrary/Samples/Audit/DownloadLogSample.cs
ClientLibrary/Samples/ClientSamples.csproj
ClientLibrary/Samples/ClientSamplesProgram.cs
ClientLibrary/Samples/packages.config

Adding samples for Audit and updating the nuget package versions

---

ClientLibrary/Samples/Work/BoardsSample.cs

added getbacklogs sample

---

ClientLibrary/Samples/Release/ReleasesSample.cs

Add example with multiple expands

---

ClientLibrary/Samples/WorkItemTracking/WorkItemsSample.cs

There is "to do" for this.
Instead of "foreach" over all the fields I using Linq to get the wefField name.

Improve getting "wefField" in "UpdateWorkItemBoardColumn" Method
